sudo: required
services:
    - docker

before_install:
    - docker build -t ntwdock/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ntwdock/react-test npm test

after_success:
    - docker build -t ntwdock/multi-client ./client
    - docker build -t ntwdock/multi-nginx ./nginx
    - docker build -t ntwdock/multi-server ./server
    - docker build -t ntwdock/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push ntwdock/multi-client
    - docker push ntwdock/multi-nginx
    - docker push ntwdock/multi-server
    - docker push ntwdock/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-066260044442
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
